source 'https://github.com/ModulizationTestOrg/huhsxSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'huhsxModulA_Example' do
  pod 'huhsxModulA', :path => '../'

end
